language: python
python:
- '2.7'
branches:
  only: master
install:
- /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
- echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
- brew tap aws/tap
- brew install aws-sam-cli
- sam --version
before_script:
- chmod +x ./test.sh
script:
- ./test.sh
env:
  global:
    - AWS_ACCESS_KEY_ID=EMPTY
    - AWS_SECRET_ACCESS_KEY=EMPTY
    - AWS_DEFAULT_REGION=us-east-1
