language: python
python:
- '2.7'
branches:
  only: master
install:
- pip install aws-sam-cli
before_script:
- chmod +x ./test.sh
script:
- ./test.sh
env:
  global:
    - AWS_ACCESS_KEY_ID=EMPTY
    - AWS_SECRET_ACCESS_KEY=EMPTY
